//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Official.Persistence.EFCore.Resourse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceEntity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceEntity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Official.Persistence.EFCore.Resourse.ResourceEntity", typeof(ResourceEntity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش ها.
        /// </summary>
        public static string AppRole {
            get {
                return ResourceManager.GetString("AppRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصیات نقش ها.
        /// </summary>
        public static string AppRoleClaim {
            get {
                return ResourceManager.GetString("AppRoleClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string AppUser {
            get {
                return ResourceManager.GetString("AppUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصیات کاربران.
        /// </summary>
        public static string AppUserClaim {
            get {
                return ResourceManager.GetString("AppUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود کاربران.
        /// </summary>
        public static string AppUserLogin {
            get {
                return ResourceManager.GetString("AppUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربران.
        /// </summary>
        public static string AppUserRole {
            get {
                return ResourceManager.GetString("AppUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجوز کاربران.
        /// </summary>
        public static string AppUserToken {
            get {
                return ResourceManager.GetString("AppUserToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقایع سیستم.
        /// </summary>
        public static string AuditEntry {
            get {
                return ResourceManager.GetString("AuditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جرئیات وقایع سیستم.
        /// </summary>
        public static string AuditEntryProperty {
            get {
                return ResourceManager.GetString("AuditEntryProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شناسنامه ای افراد.
        /// </summary>
        public static string BirthCertificate {
            get {
                return ResourceManager.GetString("BirthCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دفترچه تماس افراد.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوست مدارک سوابق آموزشی.
        /// </summary>
        public static string DegreeAttach {
            get {
                return ResourceManager.GetString("DegreeAttach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات آموزشی.
        /// </summary>
        public static string EducationalInfo {
            get {
                return ResourceManager.GetString("EducationalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کمبوهای ثابت.
        /// </summary>
        public static string Enumuration {
            get {
                return ResourceManager.GetString("Enumuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالت های استخدامی.
        /// </summary>
        public static string HireStage {
            get {
                return ResourceManager.GetString("HireStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوابق آموزشی.
        /// </summary>
        public static string HistoryEducational {
            get {
                return ResourceManager.GetString("HistoryEducational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست انتخاب.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فردی.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسامی شهرها.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امنیت.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترم آموزشی.
        /// </summary>
        public static string Term {
            get {
                return ResourceManager.GetString("Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کاربران.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
